enum GameStatus {
    NOT_STARTED = 'NOT_STARTED',
    DEFEATED = 'DEFEATED',
    NOT_ALL_MINES_FLAGGED = 'NOT_ALL_MINES_FLAGGED',
    NOT_ALL_EMPTY_REVEALED = 'NOT_ALL_EMPTY_REVEALED',
    EMPTY_FIELD_FLAGGED = 'EMPTY_FIELD_FLAGGED',
}
export {GameStatus};