import {cardStore} from "../store/cardStore.ts";
import CardLevel from '../utils/enum/CardLevel'

export default [
    {
        title: "card.flame_wave.type_1.title",
        description: "card.flame_wave.type_1.description",
        price: 6,
        probability: 2,
        level: CardLevel.MYTHIC,
        callback: cardStore.newCard,
    },
    {
        title: "card.healing_light.type_1.title",
        description: "card.healing_light.type_1.description",
        price: 2,
        probability: 9,
        level: CardLevel.COMMON,
        callback: cardStore.newCard,
    },
    {
        title: "card.stone_spike.type_2.title",
        description: "card.stone_spike.type_2.description",
        price: 3,
        probability: 8,
        level: CardLevel.UNIQUE,
        callback: cardStore.flagRandomMine,
    },
    {
        title: "card.venom_cloud.type_3.title",
        description: "card.venom_cloud.type_3.description",
        price: 4,
        probability: 7,
        level: CardLevel.RARE,
        callback: cardStore.revealRandomField,
    },
    {
        title: "card.arcane_shield.type_1.title",
        description: "card.arcane_shield.type_1.description",
        price: 5,
        probability: 5,
        level: CardLevel.UNIQUE,
        callback: cardStore.newCard,
    },
    {
        title: "card.frost_blast.type_1.title",
        description: "card.frost_blast.type_1.description",
        price: 6,
        probability: 2,
        level: CardLevel.MYTHIC,
        callback: cardStore.newCard,
    },
    {
        title: "card.thunder_clap.type_1.title",
        description: "card.thunder_clap.type_1.description",
        price: 4,
        probability: 6,
        level: CardLevel.RARE,
        callback: cardStore.flagRandomMine,
    },
    {
        title: "card.wind_barrier.type_3.title",
        description: "card.wind_barrier.type_3.description",
        price: 7,
        probability: 1,
        level: CardLevel.LEGENDARY,
        callback: cardStore.revealRandomField,
    },
    {
        title: "card.light_arrow.type_1.title",
        description: "card.light_arrow.type_1.description",
        price: 3,
        probability: 8,
        level: CardLevel.UNIQUE,
        callback: cardStore.flagRandomMine,
    },
    {
        title: "card.shadow_strike.type_1.title",
        description: "card.shadow_strike.type_1.description",
        price: 5,
        probability: 4,
        level: CardLevel.UNIQUE,
        callback: cardStore.newCard,
    },
    {
        title: "card.crystal_barrier.type_2.title",
        description: "card.crystal_barrier.type_2.description",
        price: 4,
        probability: 5,
        level: CardLevel.RARE,
        callback: cardStore.revealRandomField,
    },
    {
        title: "card.phantom_dagger.type_1.title",
        description: "card.phantom_dagger.type_1.description",
        price: 5,
        probability: 5,
        level: CardLevel.UNIQUE,
        callback: cardStore.newCard,
    },
    {
        title: "card.blazing_sphere.type_3.title",
        description: "card.blazing_sphere.type_3.description",
        price: 7,
        probability: 1,
        level: CardLevel.LEGENDARY,
        callback: cardStore.revealRandomField,
    },
    {
        title: "card.mystic_flare.type_1.title",
        description: "card.mystic_flare.type_1.description",
        price: 3,
        probability: 8,
        level: CardLevel.UNIQUE,
        callback: cardStore.flagRandomMine,
    },
    {
        title: "card.celestial_hammer.type_1.title",
        description: "card.celestial_hammer.type_1.description",
        price: 4,
        probability: 6,
        level: CardLevel.RARE,
        callback: cardStore.flagRandomMine,
    },
    {
        title: "card.storm_burst.type_1.title",
        description: "card.storm_burst.type_1.description",
        price: 5,
        probability: 5,
        level: CardLevel.UNIQUE,
        callback: cardStore.newCard,
    },
    {
        title: "card.void_nova.type_2.title",
        description: "card.void_nova.type_2.description",
        price: 4,
        probability: 6,
        level: CardLevel.RARE,
        callback: cardStore.revealRandomField,
    },
    {
        title: "card.radiant_blast.type_1.title",
        description: "card.radiant_blast.type_1.description",
        price: 6,
        probability: 2,
        level: CardLevel.MYTHIC,
        callback: cardStore.newCard,
    },
    {
        title: "card.ethereal_wave.type_3.title",
        description: "card.ethereal_wave.type_3.description",
        price: 7,
        probability: 1,
        level: CardLevel.LEGENDARY,
        callback: cardStore.revealRandomField,
    },
    {
        title: "card.starfall.type_1.title",
        description: "card.starfall.type_1.description",
        price: 5,
        probability: 4,
        level: CardLevel.UNIQUE,
        callback: cardStore.newCard,
    }
];